name: Build and publish component

on:
  workflow_call:
    inputs:
      Registry:
        required: true
        type: string
      Tag:
        required: true
        type: string
      ImageName:
        required: true
        type: string
      Environment:
        required: true
        type: string
      GitRef:
        required: false
        type: string

jobs:
  build-and-push-container:
    runs-on: ubuntu-latest
    environment: ${{ inputs.Environment }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.GitRef }}

      - name: Log in to the Github Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.Registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.Registry }}/${{ inputs.ImageName }}

      - name: 'Create env file'
        run: |
          touch .env
          echo REACT_APP_AAD_CLIENT_ID=${{ secrets.CLIENT_ID }} >> .env
          echo REACT_APP_AAD_TENANT_ID=${{ secrets.TENANT_ID }} >> .env
          echo REACT_APP_AAD_REDIRECT_URI=/ >> .env
          echo REACT_APP_BACKEND_URL=${{ vars.BACKEND_URL }} >> .env
          echo REACT_APP_BACKEND_API_SCOPE=${{ vars.BACKEND_API_SCOPE }} >> .env
          cat .env

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          target: release
          push: true
          tags: |
            ${{ inputs.Registry }}/${{ inputs.ImageName }}/${{ inputs.Environment }}:${{ inputs.Tag }}
            ${{ inputs.Registry }}/${{ inputs.ImageName }}/${{ inputs.Environment }}:latest
          labels: ${{ steps.meta.outputs.labels }}