on:
    push:
      branches:
        - main
  
permissions:
  contents: write
  pull-requests: write

name: Release please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.PEPM_CI_APP_ID }}
          private-key: ${{ secrets.PEPM_CI_APP_SECRET }}

      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ steps.generate-token.outputs.token }}
          manifest-file: .release-please-manifest.json
          config-file: release-please-config.json
